// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkcsjukkzqgrlzdrzbgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrY3NqdWtrenFncmx6ZHJ6YmdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzOTc3NjAsImV4cCI6MjA2MTk3Mzc2MH0.1VeprM40CSGlzJy57RK0lkquVbbmGpM2mxkRnHhs0Ec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);